### ISSUE TITLE
这个问题怎么解决

### ISSUE THREAD

**Issue by schoolbag123** [pcrgvg/gvg_front#10]
![Snipaste_2021-08-29_23-23-32](https://user-images.githubusercontent.com/48409459/131255851-3b14245b-f2dc-480f-84d6-6ada3f021d52.png)

**Comment by zafkielkurumi** [comment]
是不是点击的分刀，如果是的话，先点击搜索，把作业搜出来再分刀

**Comment by schoolbag123** [comment]
是的。。。。。行吧
