### ISSUE TITLE
国服作业的rank和星级标注有问题

### ISSUE THREAD

**Issue by zangxx66** [pcrgvg/gvg_front#12]
国服作业的rank和星级全部都是5X R7，与实际情况不符，而且缺少像日服那样的文字轴，希望可以改进一下  
  
![QQ截图20211128141450](https://user-images.githubusercontent.com/14540861/143731925-06d712cd-c2a5-4680-9853-a068d2101274.png)

**Comment by zafkielkurumi** [comment]
国服作业是爬的花舞的在线文档。文档并无相关数据，网站上有相关提示
