### ISSUE TITLE
未持有角色列表似乎没有本地缓存,希望可以增加.

### ISSUE THREAD

**Issue by NeuWings** [pcrgvg/gvg_front#2]
使用环境Windows10 专业版 Edge/Chromium./测试环境IOS14 Safari.
增加未持有角色至列表后下次重新开启页面,内容丢失需要重新添加.
暂时没有看代码不清楚是功能未实现还是实现出现了问题,如果不麻烦的话...希望可以实现.

(啊,用手机测试的时候发现Safari下好像没有自适应,不过只是随口一提.)
(添加未用有box错别字了!)

提前辛苦啦.

**Comment by zafkielkurumi** [comment]
我并未做手机的适配,后续可以加
本地缓存明天加上
