### ISSUE TITLE
搜索结果搜出了两个未拥有的角色

### ISSUE THREAD

**Issue by swearl** [pcrgvg/gvg_front#9]
未有的角色中, 选择了春吃和卯月....但搜索结果却出了这两人....

![图片](https://user-images.githubusercontent.com/469084/123430170-6fd98a00-d5fa-11eb-9a8b-0979c039862f.png)

![图片](https://user-images.githubusercontent.com/469084/123430217-7ff16980-d5fa-11eb-98b4-6cd445a6afc6.png)

**Comment by zafkielkurumi** [comment]
未拥有角色针对筛刀起作用,搜索页面是显示所有结果,详情查看右上角的帮助
